GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Kaloyan Dimitrov",
    "number": "0889467788"
}

###

DELETE http://localhost:3001/api/persons/50175